### ISSUE TITLE
where's 'calib_camera_lidar.txt' file

### ISSUE THREAD

**Issue by YueSun0609** [TUMFTM/DPFT#1]
Hi,

Thank you for your work! May I ask where I can find the 'calib_camera_lidar.txt' file? Since I downloaded the data from Google Driver and there's no 'calib_camera_lidar.txt' file inside 'info_calib' folder.

**Comment by ffent** [comment]
Hi @YueSun0609 ,

first of all, thanks for your interest in our work. It is correct, that the calib_camera_lidar.txt file is not included in the downloadable files from Google Drive. Therefore, we reached out to the original authors of the K-Radar dataset and they provided a lidar to camera calibration for us.

To fix this issue, just create a `calib_camera_lidar.txt` file under the `data/kradar/raw/1/info_calib/` folder and insert the following values.

```
rx, rxy, rxz, tx, ryx, ry, ryz, ty, rzx, rzy, rz, tz
629.238090, -527.036820, -4.59938064, 1413.21630, 372.013478, 9.42970300, -559.685543, 1076.37845, 0.999925370, 0.0122165356, 0.000106612091, 1.84000000
```

However, as pointed out in our [paper](https://arxiv.org/pdf/2404.03015) (Section 4.3) the calibration seems not to be perfect and calibration errors can be observed, which could have a negative impact on the performance. To counteract this, we have tried to fine-tune the provided calibration parameters by using the [manual calibration tool](https://github.com/kaist-avelab/K-Radar) provided by K-Radar, but it is very difficult to tune them manually. We also tried to use automated calibration tools from the [OpenCalib](https://github.com/PJLab-ADG/SensorsCalibration) toolbox but without any success. Ultimately, we have used the provided calibration parameters for all of our tests.

**Comment by YueSun0609** [comment]
> Hi @YueSun0609 ,
> 
> first of all, thanks for your interest in our work. It is correct, that the calib_camera_lidar.txt file is not included in the downloadable files from Google Drive. Therefore, we reached out to the original authors of the K-Radar dataset and they provided a lidar to camera calibration for us.
> 
> To fix this issue, just create a `calib_camera_lidar.txt` file under the `data/kradar/raw/1/info_calib/` folder and insert the following values.
> 
> ```
> rx, rxy, rxz, tx, ryx, ry, ryz, ty, rzx, rzy, rz, tz
> 629.238090, -527.036820, -4.59938064, 1413.21630, 372.013478, 9.42970300, -559.685543, 1076.37845, 0.999925370, 0.0122165356, 0.000106612091, 1.84000000
> ```
> 
> However, as pointed out in our [paper](https://arxiv.org/pdf/2404.03015) (Section 4.3) the calibration seems not to be perfect and calibration errors can be observed, which could have a negative impact on the performance. To counteract this, we have tried to fine-tune the provided calibration parameters by using the [manual calibration tool](https://github.com/kaist-avelab/K-Radar) provided by K-Radar, but it is very difficult to tune them manually. We also tried to use automated calibration tools from the [OpenCalib](https://github.com/PJLab-ADG/SensorsCalibration) toolbox but without any success. Ultimately, we have used the provided calibration parameters for all of our tests.

Got it! Thank you so much for your explanation!
