### ISSUE TITLE
Nice Work!!Can provide the trained weights?

### ISSUE THREAD

**Issue by xxk123456** [TUMFTM/DPFT#4]
Great work! Can you provide the trained weights? Thanks a lot

**Comment by ffent** [comment]
Hi @xxk123456 ,

thanks for your interest in our work. We will release the pre-trained weights as soon as the paper is published.

Since this issue is identical to #2, I will close this to simplify issue tracking.

**Comment by ffent** [comment]
Pre-trained model weights have been added by e42c15e06650a87784acc42d387b7cd7b6ac165c
